### ISSUE TITLE
Add live preview search for songs

### ISSUE THREAD

**Issue by wethegreenpeople** [wethegreenpeople/PartyPlaylists#29]
Should see song search results as you're searching for a song in the room

**Comment by toastmalone** [comment]
I have the javascript written. Could use some help displaying it properly though. I would like a drop-down select list directly below the search box.

https://github.com/wethegreenpeople/PartyPlaylists/tree/ToastMaloneDev

**Comment by wethegreenpeople** [comment]
Added some comments on your last commit. Let me know if you want to hop in discord later we can take a look at how to populate the select list!

**Comment by toastmalone** [comment]
Submitted another commit. I would like to get your thoughts on updating the datalist to prevent more than 5 results and remove duplicates.

**Comment by toastmalone** [comment]
Live search is working now. A few things need to be addressed still.

- Should we clear input on adding a new song? Currently, it allows for multiple selections.
- The javascript that the live search and custom list depend on need to be cleaned up and structured better
- Currently passing the unique Spotify song ID to the RoomVM. I was unable to verify if it could add a song because someone changed a column in the database...

**Comment by toastmalone** [comment]
Live search is good for now. Committed, merged with master, and merged the pull request. It should be live on the site soon.
